# Generated by Django 6.0.1 on 2026-02-02 09:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostPayRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('from_amount', models.IntegerField()),
                ('to_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_coordinates', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='/static/user-profile-picture/default-profile-avatar.png', null=True, upload_to='static/user-profile-picture/')),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('ALUMNI', 'Alumni'), ('EMPLOYER', 'Employer')], default='ADMINISTRATOR', max_length=50)),
                ('account_status', models.CharField(choices=[('ACTIVATED', 'Activated'), ('VERIFICATION', 'Verification'), ('DECLINED', 'Declined'), ('ON-HOLD', 'On Hold')], default='VERIFICATION', max_length=50)),
                ('declined_remarks', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlumniCertificationsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.TextField()),
                ('certificate_description', models.TextField()),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN REVIEW', 'In Review'), ('INTERVIEW', 'Interview'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired'), ('FINISHED', 'Finished')], default='PENDING', max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJobCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.FileField(upload_to='static/cover-letter/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumnijob')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJobResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='static/resume/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumnijob')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniLanguagesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniScaleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_appearance', models.IntegerField()),
                ('manner_of_speaking', models.IntegerField()),
                ('physical_condition', models.IntegerField()),
                ('mental_alertness', models.IntegerField()),
                ('self_confidence', models.IntegerField()),
                ('ability_to_present_ideas', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('student_performance_rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniSkillsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/announcement/')),
                ('can_message', models.CharField(choices=[('1', 'Can Message'), ('0', 'Cannot Message')], default='0', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniEducationalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_highlights', models.TextField()),
                ('year_graduated', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationcourse')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('business_type', models.CharField(choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private'), ('NON-GOVERNMENTAL ORGANIZATION', 'Ngo'), ('FREELANCE', 'Freelance')], max_length=50)),
                ('business_permit', models.FileField(upload_to='static/supporting-document/')),
                ('business_permit_remarks', models.TextField(blank=True, null=True)),
                ('business_permit_status', models.CharField(choices=[('VERIFICATION', 'Verification'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='VERIFICATION', max_length=50)),
                ('bir_2303', models.FileField(upload_to='static/supporting-document/')),
                ('bir_2303_status', models.CharField(choices=[('VERIFICATION', 'Verification'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='VERIFICATION', max_length=50)),
                ('bir_2303_remarks', models.TextField(blank=True, null=True)),
                ('sec_dti_reg', models.FileField(upload_to='static/supporting-document/')),
                ('sec_dti_reg_status', models.CharField(choices=[('VERIFICATION', 'Verification'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='VERIFICATION', max_length=50)),
                ('sec_dti_reg_remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumnijob')),
                ('to_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('location_coordinates', models.TextField()),
                ('workplace_option', models.CharField(choices=[('ON-SITE', 'On Site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], default='ON-SITE', max_length=255)),
                ('work_type', models.CharField(choices=[('FULL-TIME', 'Full Time'), ('PART-TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual')], default='FULL-TIME', max_length=255)),
                ('pay_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually')], default='HOURLY', max_length=255)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('min_general_appearance', models.IntegerField()),
                ('min_manner_of_speaking', models.IntegerField()),
                ('min_physical_condition', models.IntegerField()),
                ('min_mental_alertness', models.IntegerField()),
                ('min_self_confidence', models.IntegerField()),
                ('min_ability_to_present_ideas', models.IntegerField()),
                ('min_communication_skills', models.IntegerField()),
                ('min_student_performance_rating', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpostpayrange')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJobArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpost')),
            ],
        ),
        migrations.AddField(
            model_name='alumnijob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpost'),
        ),
        migrations.CreateModel(
            name='JobPostCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationcourse')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHAT', 'Chat'), ('JOB_POST', 'Job Post')], default='CHAT', max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('redirect_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='app.jobpost')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
