# Generated by Django 6.0.1 on 2026-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notificationviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
